
#pragma once

///NOTE: Negative static gas stands for a dynamic gas price which needs to be added to the price

#define SGAS_STOP 0
#define SGAS_ADD 3
#define SGAS_MUL 5
#define SGAS_SUB 3
#define SGAS_DIV 5
#define SGAS_SDIV 5
#define SGAS_MOD 5
#define SGAS_SMOD 5
#define SGAS_ADDMOD 8
#define SGAS_MULMOD 8
#define SGAS_EXP -10
#define SGAS_SIGNEXTEND 5
#define SGAS_LT 3
#define SGAS_GT 3
#define SGAS_SLT 3
#define SGAS_SGT 3
#define SGAS_EQ 3
#define SGAS_ISZERO 3
#define SGAS_AND 3
#define SGAS_OR 3
#define SGAS_XOR 3
#define SGAS_NOT 3
#define SGAS_BYTE 3
#define SGAS_SHL 3
#define SGAS_SHR 3
#define SGAS_SAR 3
#define SGAS_SHA3 -30
#define SGAS_ADDRESS 2
#define SGAS_BALANCE -100
#define SGAS_ORIGIN 2
#define SGAS_CALLER 2
#define SGAS_CALLVALUE  2
#define SGAS_CALLDATALOAD 3
#define SGAS_CALLDATASIZE 2
#define SGAS_CALLDATACOPY -3
#define SGAS_CODESIZE 2
#define SGAS_CODECOPY -2
#define SGAS_GASPRICE 2
#define SGAS_EXTCODESIZE -100
#define SGAS_EXTCODECOPY -100
#define SGAS_RETURNDATASIZE 2
#define SGAS_RETURNDATACOPY -3
#define SGAS_EXTCODEHASH -100
#define SGAS_BLOCKHASH 20
#define SGAS_COINBASE 2
#define SGAS_TIMESTAMP 2
#define SGAS_NUMBER 2
#define SGAS_DIFFICULTY 2
#define SGAS_GASLIMIT 2
#define SGAS_CHAINID 2
#define SGAS_SELFBALANCE 5
#define SGAS_BASEFEE 2
#define SGAS_POP 2
#define SGAS_MLOAD -3
#define SGAS_MSTORE -3
#define SGAS_MSTORE8 -3
#define SGAS_SLOAD -100
#define SGAS_SSTORE -100
#define SGAS_JUMP 8
#define SGAS_JUMPI 10
#define SGAS_PC 2
#define SGAS_MSIZE 2
#define SGAS_GAS 2
#define SGAS_JUMPDEST 1
#define SGAS_PUSH 3
#define SGAS_DUP 3
#define SGAS_SWAP 3
#define SGAS_LOG0 -375
#define SGAS_LOG1 -750
#define SGAS_LOG2 -1125
#define SGAS_LOG3 -1500
#define SGAS_LOG4 -1875
#define SGAS_CREATE -32000
#define SGAS_CALL -100
#define SGAS_CALLCODE -100
#define SGAS_RETURN -0
#define SGAS_DELEGATECALL -100
#define SGAS_CREATE2 -32000
#define SGAS_STATICCALL -100
#define SGAS_REVERT -0
#define SGAS_INVALID 0
#define SGAS_SELFDESTRUCT -5000
